from langchain_google_genai import GoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain.vectorstores.chroma import Chroma
from get_embedding import get_embedding_function
